services:
  - type: web
    name: api-forcemap
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: api-forcemap
          property: port
      - key: HOST
        value: 0.0.0.0
