services:
  - type: web
    name: api-forcemap
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm prestart:prod && pnpm start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: api-forcemap
          property: port
      - key: HOST
        value: 0.0.0.0
      - key: PNPM_VERSION
        value: 10.13.1
